config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  #get 'welcome/index'
  #root 'welcome#index'
  devise_for :users
  resources :posts do
  	resources :comments
  end
  root 'posts#index'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  get '/about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :post
  belongs_to :user
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum:6 }
  validates :body, presence: true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
  	has_many :comments, dependent: :destroy
  	has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
      has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
      has_many :followers, through: :passive_relationships, source: :follower

      has_many :following, through: :active_relationships, source: :followed


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  

# Returns a user's status feed.
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    post.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)

  end
# Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_post
	before_action :find_comment, only:[:destroy, :edit, :update, :comment_ower]
	before_action :comment_ower, only:[:destroy, :edit, :update]
	def create
		@comment = @post.comments.create(params[:comment].permit(:content))
		@comment.user_id= current_user.id
		@comment.save

		if @comment.save
		redirect_to post_path(@post)
		else
		render 'new'
		end 
	end

	def destroy
		@comment.destroy

		redirect_to post_path(@post)
	end

	def edit
	end

	def update
		if @comment.update(params[:comment].permit(:content))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

private
def find_post
		@post = Post.find(params[:post_id])
	end

	def find_comment 
		@comment = @post.comments.find(params[:id])
	end

	def comment_ower
		unless current_user.id = @comment.user_id
			flash[:notice] = "you shall not pass"
			redirect_to @post
			
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
def index
	@posts = Post.all.order('created_at DESC')
end

def show
	@post = Post.find(params[:id])
	@comments = Comment.where(post_id: @post).order('created_at DESC')
end

def new
	@post = Post.new
end

def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
end
def edit
	@post = Post.find(params[:id])
end
def update
	@post = Post.find(params[:id])

	if @post.update(params[:post].permit(:title, :body))
		redirect_to @post
	else
		render 'edit'
	end
end

def destroy
	@post = Post.find(params[:id])
	@post.destroy

	redirect_to root_path
end

private
	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :user_signed_in?

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 before_action :user_signed_in?, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]

  def index
      @users = User.paginate(page: params[:page])
  end
  
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
	 def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>
<div class="text-center">
<%= comment.user.email %>
<p><%= comment.content %> </p>

<% if user_signed_in? %>
<% if current_user == comment.user %>
<%= link_to "Delete comment  |", [comment.post,comment], method: :Delete, data: {confirm: "Are you sure ?"} %>
<%= link_to "Edit comment", edit_post_comment_path(comment.post,comment) %>
<%end%>
<%end%>
<%end%>
<%= render 'comments/form' %>
</div>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= f.text_area :content %>
	<%= f.submit %>
<% end %>
<%end %>

app/views/comments/edit.html.erb
<%= form_for([@post,@comment]) do |f| %>
	<%= f.text_area :content %>
	<%= f.submit %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag    'application',  'http://fonts.googleapis.com/css?family=Releway:400,700' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="text-left">
		<div id="logo">
			<%= link_to root_path do %>
				<%= image_tag "logo2.jpeg" %>
				<% end %>
		</div>
		<ul>
			<li><%= link_to "Blog",root_path %></li>
			<li><%= link_to "Blogger", users_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>
	</div>

	<div class="text-center">
		<div class="text-left">
			<% if user_signed_in? %>
				<%= link_to "NEW POST   _|_  ", new_post_path %>
				<%= link_to "LOG OUT", destroy_user_session_path, method: :delete %>
			<% else %>
			<%= link_to "SIGN_IN | ", user_session_path %>
			<%= link_to "SIGN_UP", new_user_registration_path %>
			<%end%>
		</div>
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class:"alert") %>
		<% end %>

			<%= yield %>
	</div>


</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "" %>
	</div>
	<div class="panel-body">
		
		<h1>Doan</h1>
		<h5>Welcome to Blog</h5>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do|f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "eroor") %> this post from saving</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
	<%= f.submit %>
	</p>

	<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
<h1>Edit posts</h1>

<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post_wrapper">
	<h2 class="title"><%= link_to post.title, post %></h2>
	<p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>	
</div>

<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<div class="text-center">
<h1>New posts</h1>

<%= render 'form' %>
</div>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="text-center"><%= @post.title %></h1>
  <h5 class="text-center">Submitted <%= time_ago_in_words(@post.created_at)%> ago</h5>
  <p class="text-center">
  <%=  @post.body %>
  </p>
   <div class="text-center">
  <% if (current_user && @post == current_user.posts.find_by(id: params[:id])) %> 
 
  <%= link_to "Edit post   |", edit_post_path %>
  <%= link_to "Delete post", post_path(@post), method: :delete, data: {confirm: "Are you sure ?"} %>
  <%end%>
  
 <%= render 'comments/comment' %>
</div>	
</div>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>  

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user.id == @user.id %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= link_to user.email, user %>
</li>

app/views/users/index.html.erb
<div class="text-center">
<% @users = User.all %>
<% @users.each do |user| %>
  <%= user.id %><br/>
  <%= link_to user.email, user_path(user)%><br/>
<% end %>
</div>

app/views/users/show.html.erb
<div class="row">
 
  <div class="col-md-8">
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <%= render 'follow_form' if user_signed_in? %>
    <% if @user.posts.any? %>
      <h3>posts (<%= @user.posts.count %>)</h3>
      <ol class="posts">
        <%= @user.posts.each do |post| %>
          <%= link_to post.title, post_path(post) %><br>
        <% end %>
      </ol>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.email %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>posts:</b> <%= @user.posts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
    <% end %>
  </div>
</div>